config/routes.rb
Rails.application.routes.draw do
  resources :countries
  resources :continentes
  resources :posts
  resources :authors
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/continente.rb
class Continente < ApplicationRecord
  has_many :countries
end

app/controllers/continentes_controller.rb
class ContinentesController < ApplicationController
  before_action :set_continente, only: %i[ show edit update destroy ]

  # GET /continentes or /continentes.json
  def index
    @continentes = Continente.all
  end

  # GET /continentes/1 or /continentes/1.json
  def show
  end

  # GET /continentes/new
  def new
    @continente = Continente.new
  end

  # GET /continentes/1/edit
  def edit
  end

  # POST /continentes or /continentes.json
  def create
    @continente = Continente.new(continente_params)

    respond_to do |format|
      if @continente.save
        format.html { redirect_to @continente, notice: "Continente was successfully created." }
        format.json { render :show, status: :created, location: @continente }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @continente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /continentes/1 or /continentes/1.json
  def update
    respond_to do |format|
      if @continente.update(continente_params)
        format.html { redirect_to @continente, notice: "Continente was successfully updated." }
        format.json { render :show, status: :ok, location: @continente }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @continente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /continentes/1 or /continentes/1.json
  def destroy
    @continente.destroy
    respond_to do |format|
      format.html { redirect_to continentes_url, notice: "Continente was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_continente
      @continente = Continente.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def continente_params
      params.require(:continente).permit(:name)
    end
end

app/helpers/continentes_helper.rb
module ContinentesHelper
end

app/views/continentes/_form.html.erb
<%= form_with(model: continente) do |form| %>
  <% if continente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(continente.errors.count, "error") %> prohibited this continente from being saved:</h2>

      <ul>
        <% continente.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/continentes/edit.html.erb
<h1>Editing Continente</h1>

<%= render 'form', continente: @continente %>

<%= link_to 'Show', @continente %> |
<%= link_to 'Back', continentes_path %>

app/views/continentes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Continentes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @continentes.each do |continente| %>
      <tr>
        <td><%= continente.name %></td>
        <td><%= link_to 'Show', continente %></td>
        <td><%= link_to 'Edit', edit_continente_path(continente) %></td>
        <td><%= link_to 'Destroy', continente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Continente', new_continente_path %>

app/views/continentes/new.html.erb
<h1>New Continente</h1>

<%= render 'form', continente: @continente %>

<%= link_to 'Back', continentes_path %>

app/views/continentes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @continente.name %>
</p>

<%= link_to 'Edit', edit_continente_path(@continente) %> |
<%= link_to 'Back', continentes_path %>